version: '3.8'

services:
  agent-laboratory:
    build: .
    image: agent-laboratory
    container_name: agent-laboratory
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - TF_FORCE_GPU_ALLOW_GROWTH=true
      - TF_CPP_MIN_LOG_LEVEL=2
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    volumes:
      - .:/workspace
      - ./output:/workspace/output
    working_dir: /workspace
    user: "1000:1000"
    tty: true
    stdin_open: true